PRODUCT_PACKAGES += \
    CompanionDeviceManagerOverlay \
    DeviceDiagnosticsOverlay \
    FlipendoOverlay \
    NfcOverlayCommon \
    PixelBatteryHealthOverlay \
    SafetyRegulatoryInfoOverlay \
    SettingsGoogleNoTelephonyOverlay \
    SettingsGoogleTangorproOverlay \
    SettingsGoogleTangorproOverlayRRO \
    SettingsProviderOverlay \
    SfpsOverlayTablet \
    SimAppDialogOverlay \
    StorageManagerGoogleOverlay \
    SystemUITitanOverlay \
    TeleServiceOverlay \
    TelecomOverlay \
    TelephonyProviderOverlay \
    TitanConfigOverlay \
    TitanNexusLauncherOverlay \
    TitanSettingsOverlay \
    TitanSettingsProviderOverlay \
    TitanSysuiConfigOverlay \
    TraceurOverlay \
    WildlifeSettingsVpnOverlay2022 \
    WildlifeSysuiVpnOverlay2022 \
    SettingsGoogleTangorproOverlayVendorRRO \
