PRODUCT_PACKAGES += \
    CompanionDeviceManagerOverlay \
    DMServiceOverlay \
    DeviceDiagnosticsOverlay \
    FlipendoOverlay \
    NfcOverlayCommon \
    PearlOverlay2024 \
    PixelBatteryHealthOverlay \
    PixelDisplayService__tokay__auto_generated_rro_product \
    PixelSupportPrebuiltOverlay \
    SafetyRegulatoryInfoOverlay \
    SettingsGoogleTokayOverlay \
    SettingsGoogleTokayOverlayRRO \
    SettingsProviderOverlay \
    SimAppDialogOverlay \
    StorageManagerGoogleOverlay \
    SystemUIGoogleOverlay \
    TeleServiceOverlay \
    TelecomOverlay \
    TelephonyProviderOverlay \
    TraceurOverlay \
    TrafficLightFaceOverlay \
    UdfpsOverlay \
    UltrasonicOverlay \
    WildlifeSettingsVpnOverlay2022 \
    WildlifeSysuiVpnOverlay2022 \
    SettingsGoogleTokayOverlayVendorRRO \
