PRODUCT_PACKAGES += \
    CompanionDeviceManagerOverlay \
    DMServiceOverlay \
    DeviceAsWebcamOriole \
    DeviceDiagnosticsOverlay \
    FlipendoOverlay \
    NfcOverlayCommon \
    NfcOverlayOriole \
    PixelBatteryHealthOverlay \
    SafetyRegulatoryInfoOverlay \
    SettingsGoogleOrioleOverlay \
    SettingsGoogleOrioleOverlayRRO \
    SettingsProviderOverlay \
    SimAppDialogOverlay \
    StorageManagerGoogleOverlay \
    SystemUIGoogleOverlay \
    TeleServiceOverlay \
    TelecomOverlay \
    TelephonyProviderOverlay \
    TraceurOverlay \
    UdfpsOverlay \
    SettingsGoogleOrioleOverlayVendorRRO \
